### PR TITLE
fixes #386

### LINKED ISSUE #386: Batch get that exceeds provisionedthroughput or size limit results in `table metadata entry for 'SHARED.mt_sharedtablestatic_s_nolsi' does not exist in SHARED._tablemetadata` error
to reproduce:
- write 100 300KB records
- attempt to read them in batch

expected result:
- you get back ~52 items and 48 unprocessedkeys

actual result: "`table metadata entry for 'SHARED.mt_sharedtablestatic_s_nolsi' does not exist in SHARED._tablemetadata`" error

### PR DESCRIPTION
**Pull request by msgroi**

### CODE REVIEW

File: src/main/java/com/salesforce/dynamodbv2/mt/mappers/sharedtable/impl/MtAmazonDynamoDbBySharedTable.java [hunk 1]
```diff
@@ -158,6 +158,16 @@ protected MtAmazonDynamoDbContextProvider getMtContext() {
...
+        // validate
+        unqualifiedBatchGetItemRequest.getRequestItems().values().forEach(keysAndAttributes -> {
+            checkArgument(keysAndAttributes.getAttributesToGet() == null,
+                "attributesToGet are not supported on BatchGetItemRequest's");
+            checkArgument(keysAndAttributes.getProjectionExpression() == null,
+                "projectionExpression is not supported on BatchGetItemRequest's");
+            checkArgument(keysAndAttributes.getExpressionAttributeNames() == null,
+                "expressionAttributeNames are not supported on BatchGetItemRequest's");
+        });
+
```
Comment (msgroi) [inline src/main/java/com/salesforce/dynamodbv2/mt/mappers/sharedtable/impl/MtAmazonDynamoDbBySharedTable.java]: This is an unrelated change.  The `KeysAndAttributes` object that gets return as part of the unprocessedKeys has 5 things ... keys, consistentRead flag, attributesToGet, projectionExpression, and expressionAttributeNames.  Batch get tests aren't testing the latter 4.  I suspect regular get tests aren't either.  I think it's better to fail than to silently ignore them.  Maybe I should add the same validation to the non-batch get?  Should I disallow consistentRead?  I chose to support it because it's a flag that I can copy over.  But there's no test for it yet.

File: src/test/java/com/salesforce/dynamodbv2/testsupport/TestSupport.java [hunk 2]
```diff
@@ -100,7 +100,8 @@
             assertEquals(1, tablesInResult.size());
             assertEquals(tableName, Iterables.getOnlyElement(tablesInResult));
             resultItems.addAll(batchGetItemResult.getResponses().get(tableName));
-            requestItems = batchGetItemResult.getUnprocessedKeys();
+            unprocessedKeys = batchGetItemResult.getUnprocessedKeys();
+            requestItems = unprocessedKeys;
```
Comment (msgroi) [inline src/test/java/com/salesforce/dynamodbv2/testsupport/TestSupport.java]: This was actually a bug in the test support that wasn't exercised until now.

File: src/main/java/com/salesforce/dynamodbv2/mt/mappers/sharedtable/impl/MtAmazonDynamoDbBySharedTable.java [hunk 3]
```diff
@@ -158,6 +158,16 @@ protected MtAmazonDynamoDbContextProvider getMtContext() {
      */
     @Override
     public BatchGetItemResult batchGetItem(BatchGetItemRequest unqualifiedBatchGetItemRequest) {
+        // validate
+        unqualifiedBatchGetItemRequest.getRequestItems().values().forEach(keysAndAttributes -> {
+            checkArgument(keysAndAttributes.getAttributesToGet() == null,
+                "attributesToGet are not supported on BatchGetItemRequest's");
```
Comment (horwitzj) [inline src/main/java/com/salesforce/dynamodbv2/mt/mappers/sharedtable/impl/MtAmazonDynamoDbBySharedTable.java]: "BatchGetItemRequest's" -> "BatchGetItemRequest calls" (sim. elsewhere)

File: src/test/java/com/salesforce/dynamodbv2/BatchGetTest.java [hunk 4]
```diff
@@ -55,6 +59,43 @@ void batchGet(TestArgument testArgument) {
             });
     }
 
+    /**
+     * Tests that partial results returned by batch gets are handled properly.  When partial results are returned, the
+     * {@code BatchGetItemOutcome} will contain a map of the UnprocessedKeys.  Partial results will be returned if
+     * the response size limit is exceeded, the table's provisioned throughput is exceeded, or an internal processing
+     * failure has occurred.  This test triggers partial results by exceeding the 16MB response size limit.  It does
+     * this by POSTing 100 records that are ~300KB in size(~20MB in total).  It then attempts to retrieve them in a
```
Comment (horwitzj) [inline src/test/java/com/salesforce/dynamodbv2/BatchGetTest.java]: add space: "size(~20MB" -> "size (~20MB"

File: src/test/java/com/salesforce/dynamodbv2/BatchGetTest.java [hunk 5]
```diff
@@ -55,6 +59,43 @@ void batchGet(TestArgument testArgument) {
...
+     * single batch GET call.  Partial results are returned because retrieving all 100 records in a single batch get
```
Comment (horwitzj) [inline src/test/java/com/salesforce/dynamodbv2/BatchGetTest.java]: "get" -> "GET" (at end of line)

File: src/main/java/com/salesforce/dynamodbv2/mt/mappers/sharedtable/impl/MtAmazonDynamoDbBySharedTable.java [hunk 6]
```diff
@@ -194,6 +204,22 @@ public BatchGetItemResult batchGetItem(BatchGetItemRequest unqualifiedBatchGetIt
                 tableMapping.getVirtualTable().getTableName(),
                 qualifiedItems.stream().map(keysAndAttributes ->
                     tableMapping.getItemMapper().reverse(keysAndAttributes)).collect(Collectors.toList()));
+            // map unprocessedkeys
```
Comment (horwitzj) [inline src/main/java/com/salesforce/dynamodbv2/mt/mappers/sharedtable/impl/MtAmazonDynamoDbBySharedTable.java]: "unprocessedkeys" -> "unprocessedKeys" (or "unprocessed keys")

File: src/test/java/com/salesforce/dynamodbv2/BatchGetTest.java [hunk 7]
```diff
@@ -55,6 +59,43 @@ void batchGet(TestArgument testArgument) {
...
+    @ParameterizedTest(name = "{arguments}")
+    @ArgumentsSource(DefaultArgumentProvider.class)
+    void batchGetWithUnprocessedKeys(TestArgument testArgument) {
+        testArgument.forEachOrgContext(
+            org -> {
+                final int targetRecordLength = 300 * 1024; // 300KB record
+                final int itemCount = 100;
+
+                // write records
+                IntStream.rangeClosed(1, itemCount).forEach(i -> {
```
Comment (horwitzj) [inline src/test/java/com/salesforce/dynamodbv2/BatchGetTest.java]: simplify to ```                IntStream.rangeClosed(1, itemCount).forEach(i -> testArgument.getAmazonDynamoDb()
                    .putItem(new PutItemRequest().withTableName(TABLE1).withItem(
                        ItemBuilder.builder(testArgument.getHashKeyAttrType(), HASH_KEY_OTHER_VALUE + i)
                            .someField(S, "x".repeat(targetRecordLength)).build())));```

Comment (horwitzj) [reply src/test/java/com/salesforce/dynamodbv2/BatchGetTest.java]: simplify to
```
                IntStream.rangeClosed(1, itemCount).forEach(i -> testArgument.getAmazonDynamoDb()
                    .putItem(new PutItemRequest().withTableName(TABLE1).withItem(
                        ItemBuilder.builder(testArgument.getHashKeyAttrType(), HASH_KEY_OTHER_VALUE + i)
                            .someField(S, "x".repeat(targetRecordLength)).build())));
```

File: pom.xml [hunk 8]
```diff
@@ -159,6 +159,10 @@
                     <!-- Allows for running failsafe tests while skipping surefire tests.
                          See https://stackoverflow.com/questions/6612344/prevent-unit-tests-but-allow-integration-tests-in-maven -->
                     <skipTests>${skip.surefire.tests}</skipTests>
+                    <!-- This is necessary to trigger BatchGetTest to happen after ScanTest
+                         until such time that ScanTest's performance doesn't depend on the size
+                         of data insert by BatchGetTest -->
```
Comment (horwitzj) [inline pom.xml]: "insert" -> "inserted"

Comment (msgroi) [reply pom.xml]: fixed in 3df175a474f2ba2b179105b941b1fb6c869b980b

File: src/main/java/com/salesforce/dynamodbv2/mt/mappers/sharedtable/impl/MtAmazonDynamoDbBySharedTable.java (hunk 1 above)
Comment (msgroi) [reply src/main/java/com/salesforce/dynamodbv2/mt/mappers/sharedtable/impl/MtAmazonDynamoDbBySharedTable.java]: OK, I am validating that there is no consistentRead set in addition to attributesToGet, projectionExpression, and expressionAttributeNames.  And I'm validating the same in `getItem()`.
